const URL="https://zvvfjmadziyuwutdresz.supabase.co",KEY="sb_publishable_5tzbKmV1EQZTDFLtRPLhnQ_POvlG0Xc",USER="Hasan",PASS="25808";let q=0,rows=[];
const $=id=>document.getElementById(id),H=()=>({"Content-Type":"application/json","apikey":KEY,"Authorization":"Bearer "+KEY});
async function rpc(fn,body){let r=await fetch(`${URL}/rest/v1/rpc/${fn}`,{method:"POST",headers:H(),body:JSON.stringify(body)}),t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function show(tab){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(tab).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab));if(tab==="results")render()}
document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>show(x.dataset.tab));document.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>show(x.dataset.open));
$("toggle").onclick=()=>{$("password").type=$("password").type==="password"?"text":"password"};
$("loginForm").onsubmit=e=>{e.preventDefault();if($("username").value.trim()===USER&&$("password").value===PASS){sessionStorage.teacher="1";openApp()}else $("loginError").textContent="اسم المستخدم أو كلمة المرور غير صحيحة."};
$("logout").onclick=()=>{sessionStorage.removeItem("teacher");location.reload()};
function openApp(){$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");$("date").textContent=new Date().toLocaleDateString("ar-EG",{weekday:"long",year:"numeric",month:"long",day:"numeric"});if(!document.querySelector(".question"))addQuestion();load()}
function addQuestion(){q++;let d=document.createElement("div");d.className="question";d.innerHTML=`<div class="qbar"><span class="qnum">السؤال ${q}</span><button class="remove">حذف</button></div><label>السؤال</label><input class="qt" placeholder="اكتب نص السؤال"><label>الاختيارات — حدد الإجابة الصحيحة</label><div class="opts">${[0,1,2,3].map(i=>`<div class="opt"><input type="radio" name="q${q}" value="${i}" ${i===0?"checked":""}><input class="qo" placeholder="الاختيار ${i+1}"></div>`).join("")}</div>`;d.querySelector(".remove").onclick=()=>d.remove();$("questions").append(d)}
$("add").onclick=addQuestion;
$("make").onclick=async()=>{try{let title=$("title").value.trim()||"امتحان اللغة العربية",duration=+$("duration").value,questions=[...document.querySelectorAll(".question")].map(d=>({text:d.querySelector(".qt").value.trim(),options:[...d.querySelectorAll(".qo")].map(x=>x.value.trim()),correct_index:+d.querySelector("input[type=radio]:checked").value}));if(!duration||!questions.length||questions.some(x=>!x.text||x.options.some(y=>!y)))throw Error("أكمل بيانات الامتحان والأسئلة.");let x=await rpc("create_public_exam",{p_title:title,p_duration_minutes:duration,p_questions:questions}),code=Array.isArray(x)?x[0]?.code:x?.code;if(!code)throw Error("لم يتم إنشاء رمز الامتحان.");$("link").value=`${location.origin}${location.pathname.replace(/teacher\\.html$/,"index.html")}?exam=${encodeURIComponent(code)}`;$("share").classList.remove("hidden")}catch(e){alert(e.message)}};
$("copy").onclick=async()=>{await navigator.clipboard.writeText($("link").value);$("copy").textContent="تم النسخ ✓";setTimeout(()=>$("copy").textContent="نسخ الرابط",1300)};
function card(r,i){let s=+r.score||0,t=+r.total_questions||0,w=Math.max(0,t-s),p=t?Math.round(s/t*100):0;return `<article class="student-card"><span class="rank ${i===0?"first":i===1?"second":i===2?"third":""}">${i+1}</span><div class="student-top"><div><div class="student-name">👤 ${esc(r.student_name||"اسم الطالب غير متاح")}</div><span class="exam-name">${esc(r.exam_title||"امتحان")}</span></div><div class="percentage ${p>=50?"good":""}">${p}%</div></div><div class="details"><span class="pill ok">✓ صحيح: ${s}</span><span class="pill bad">✕ خطأ: ${w}</span><span class="pill">الدرجة: ${s} / ${t}</span></div></article>`}
function render(){let term=$("search").value.trim().toLowerCase(),sort=$("sort").value;let a=rows.filter(r=>(r.student_name||"").toLowerCase().includes(term)).map(r=>({...r,_p:(+r.total_questions||0)?(+r.score||0)/(+r.total_questions)*100:0}));a.sort((x,y)=>sort==="desc"?y._p-x._p:x._p-y._p);$("rankings").innerHTML=a.length?a.map((r,i)=>card(r,i)).join(""):`<div class="student-card" style="text-align:center;color:#7186a1">📊 لا توجد نتائج مطابقة</div>`}
async function load(){try{let x=await rpc("teacher_public_results",{});rows=Array.isArray(x)?x:[];let ps=rows.map(r=>(+r.total_questions||0)?(+r.score||0)/(+r.total_questions)*100:0),avg=ps.length?Math.round(ps.reduce((a,b)=>a+b,0)/ps.length):0,best=ps.length?Math.round(Math.max(...ps)):0,bi=ps.indexOf(Math.max(...ps));$("s1").textContent=rows.length;$("s2").textContent=avg+"%";$("s3").textContent=best+"%";$("best").textContent=bi>=0?(rows[bi].student_name||"أفضل طالب"):"لا توجد نتائج";$("rTotal")&&($("rTotal").textContent=rows.length);$("recent").innerHTML=rows.slice().sort((a,b)=>(+b.score||0)-(+a.score||0)).slice(0,5).map((r,i)=>card(r,i)).join("")||`<div class="student-card" style="text-align:center;color:#7186a1">لا توجد نتائج حتى الآن</div>`;render()}catch(e){$("recent").innerHTML=`<div class="student-card">تعذر تحميل النتائج</div>`}}
$("refresh").onclick=load;$("refresh2").onclick=load;$("search").oninput=render;$("sort").onchange=render;
if(sessionStorage.teacher==="1")openApp();