const SUPABASE_URL="https://zvvfjmadziyuwutdresz.supabase.co";
const SUPABASE_KEY="sb_publishable_5tzbKmV1EQZTDFLtRPLhnQ_POvlG0Xc";
const USER="Hasan", PASS="25808"; let qid=0, cached=[]; const $=x=>document.getElementById(x);
const hdr=()=>({"Content-Type":"application/json","apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY});
async function rpc(fn,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:"POST",headers:hdr(),body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw Error(t||"Request failed");return t?JSON.parse(t):null}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function go(id){document.querySelectorAll(".section").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));const b=document.querySelector(`[data-section="${id}"]`);if(b)b.classList.add("active")}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.section));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
$("togglePass").onclick=()=>{$("password").type=$("password").type==="password"?"text":"password"};
$("loginForm").onsubmit=e=>{e.preventDefault();if($("username").value.trim()===USER&&$("password").value===PASS){sessionStorage.setItem("hasan_teacher_login","1");showDash()}else $("loginError").textContent="بيانات الدخول غير صحيحة."};
$("logoutBtn").onclick=()=>{sessionStorage.removeItem("hasan_teacher_login");location.reload()};
function showDash(){$("loginScreen").classList.add("hidden");$("dashboard").classList.remove("hidden");$("today").textContent=new Date().toLocaleDateString("ar-EG",{weekday:"long",year:"numeric",month:"long",day:"numeric"});if(!document.querySelector(".question"))addQuestion();loadResults()}
function addQuestion(){qid++;const d=document.createElement("div");d.className="question";d.innerHTML=`<div class="qtop"><span class="qnum">السؤال ${qid}</span><button class="remove">حذف</button></div><label>نص السؤال</label><input class="qt" placeholder="اكتب السؤال هنا"><label>الاختيارات</label><div class="opts">${[0,1,2,3].map(i=>`<div class="opt"><input type="radio" name="c${qid}" value="${i}" ${i===0?"checked":""}><input class="qo" placeholder="الاختيار ${i+1}"></div>`).join("")}</div>`;d.querySelector(".remove").onclick=()=>d.remove();$("questions").appendChild(d)}
$("addQuestion").onclick=addQuestion;
$("createExam").onclick=async()=>{try{const title=$("examTitle").value.trim()||"امتحان اللغة العربية",duration=+$("duration").value;const questions=[...document.querySelectorAll(".question")].map(d=>({text:d.querySelector(".qt").value.trim(),options:[...d.querySelectorAll(".qo")].map(x=>x.value.trim()),correct_index:+d.querySelector('input[type=radio]:checked').value}));if(!duration||questions.length<1||questions.some(q=>!q.text||q.options.some(x=>!x)))throw Error("أكمل بيانات الامتحان والأسئلة.");const data=await rpc("create_public_exam",{p_title:title,p_duration_minutes:duration,p_questions:questions});const code=Array.isArray(data)?data[0]?.code:data?.code;if(!code)throw Error("لم يتم استلام رمز الامتحان.");$("examLink").value=`${location.origin}${location.pathname.replace(/teacher\\.html$/,"index.html")}?exam=${encodeURIComponent(code)}`;$("linkBox").classList.remove("hidden")}catch(e){alert(e.message)}};
$("copyLink").onclick=async()=>{await navigator.clipboard.writeText($("examLink").value);$("copyLink").textContent="تم النسخ ✓";setTimeout(()=>$("copyLink").textContent="نسخ",1500)};
function resultCard(r){const score=+r.score||0,total=+r.total_questions||0,wrong=Math.max(0,total-score),pct=total?Math.round(score/total*100):0;return `<article class="result"><div><div class="student">👤 ${esc(r.student_name||"اسم الطالب غير متاح")}</div><span class="exam">${esc(r.exam_title||"امتحان")}</span></div><div class="result-right"><div class="percent ${pct>=50?"good":""}">${pct}%</div></div><div class="detail-row"><span class="pill ok">✓ صحيح: ${score}</span><span class="pill bad">✕ خطأ: ${wrong}</span><span class="pill">الدرجة: ${score}/${total}</span></div></article>`}
async function loadResults(){try{const data=await rpc("teacher_public_results",{});cached=Array.isArray(data)?data:[];const p=cached.map(r=>{const t=+r.total_questions||0;return t?(+r.score||0)/t*100:0});const avg=p.length?Math.round(p.reduce((a,b)=>a+b,0)/p.length):0,best=p.length?Math.round(Math.max(...p)):0;const bi=p.indexOf(Math.max(...p));$("studentsCount").textContent=cached.length;$("averageScore").textContent=avg+"%";$("bestScore").textContent=best+"%";$("bestStudent").textContent=bi>=0?(cached[bi].student_name||"أفضل طالب"):"لا توجد نتائج";$("rTotal").textContent=cached.length;$("rPass").textContent=avg+"%";$("rTop").textContent=best+"%";const cards=cached.length?cached.map(resultCard).join(""):`<div class="empty">📊<br>لا توجد نتائج حتى الآن</div>`;$("overviewResults").innerHTML=cached.slice(0,5).map(resultCard).join("")||`<div class="empty">لا توجد نتائج حتى الآن</div>`;$("allResults").innerHTML=cards}catch(e){$("overviewResults").innerHTML=`<div class="empty">تعذر تحميل النتائج</div>`;$("allResults").innerHTML=$("overviewResults").innerHTML}}
$("refreshResults").onclick=loadResults;$("refreshResults2").onclick=loadResults;
if(sessionStorage.getItem("hasan_teacher_login")==="1")showDash();